### ISSUE TITLE
diacritics-neutralise - "s.replace is not a function" error when string column contains pure integer value

### ISSUE THREAD

**Issue by themightystephen** [DataTables/Plugins#455]
I have a DataTable with (ajax) data loaded in one column which normally contains values of type string but sometimes contains integer values. E.g.:
```json
{
  id: 1
  name: "Company A"
  has_access: "1"
},
{
  id: 2
  name: "Company B"
  has_access: "1"
},
{
  id: 1
  name: 727
  has_access: 1
}
```
In the above, the third company is called 727, which unfortunately is returned as an integer type rather than string in the JSON. diacritics-neutralise hits a snag when it reaches processing this entry and gives an error:  `s.replace is not a function`

I managed to change the back-end which generates the JSON so that it ensures 727 is always a string ("727") - that has been my solution here. However, it may be worth making the plugin more resilient to this situation by updating the `removeDiacritics` function to cast `s` to a string to ensure it's never caught off-guard:
```js
function removeDiacritics ( s ) {
  for (var i=0, l=diacriticsMap.length; i<l; i++) {
    s = String(s).replace(diacriticsMap[i].letters, diacriticsMap[i].base);
  }
  return s; 
}
```
The above worked for me before using the server-side solution mentioned above.

**Comment by holtkamp** [comment]
The same occurred to me when using `any-number` sorting plugin and a `NULL` or integer is handed over by the back-end after inline editing a row:

https://github.com/DataTables/Plugins/blob/244f788ecf9a537b9aead6cdeca66cf5e2843377/sorting/any-number.js#L32

```js
any-number.js:32 Uncaught TypeError: Cannot read properties of null (reading 'replace')
at _anyNumberSort (any-number.js:32:11)
at DataTable.ext.type.order.any-number-asc (any-number.js:39:12)
at jquery.dataTables.min.js?version=1.13.6:4:42937
at Array.sort (<anonymous>)
at ie (jquery.dataTables.min.js?version=1.13.6:4:42765)
at u (jquery.dataTables.min.js?version=1.13.6:4:23709)
at B.<anonymous> (jquery.dataTables.min.js?version=1.13.6:4:55254)
at B.iterator (jquery.dataTables.min.js?version=1.13.6:4:52083)
at B.<anonymous> (jquery.dataTables.min.js?version=1.13.6:4:55209)
at B.draw (jquery.dataTables.min.js?version=1.13.6:4:53566)
```

Or when an integer is involved: 

```js
Uncaught TypeError: a.replace is not a function
```

Like @themightystephen I circumvented this by ensuring every value returned by the backend is a string using a PHP function like this: 

```php
    public function serializeTableRowDataArrayToJson(array $tableRowData) : string
    {
        $arrayWithStringValues = array_map(
            static fn (mixed $value) : string => strval($value),
            $tableRowData
        );

        return json_encode($arrayWithStringValues, JSON_HEX_TAG | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
    }
```

I agree that casting to a string in the plugin itself might be a better place to do?

**Comment by AllanJard** [comment]
The plugin should really just allow for non-string types. If it isn't a string it can't contain a diacritic...! I'll look into that.

**Comment by AllanJard** [comment]
The plug-in does actually cast to a string already: https://github.com/DataTables/Plugins/blob/master/sorting/src/diacritics-sort.ts#L320 . Could some one link me to a test case showing the issue so I can take a further look into it please?

**Comment by holtkamp** [comment]
@AllanJard ah, maybe I hijacked an old issue then. 

My example was about any-number.js sorting plugin: https://github.com/DataTables/Plugins/blob/244f788ecf9a537b9aead6cdeca66cf5e2843377/sorting/any-number.js#L39

**Comment by AllanJard** [comment]
Thanks for the clarification. Fix committed here: https://github.com/DataTables/Plugins/commit/257a4c7c22ec168a1f550ec1b9add8bd5f1edc78 . Assuming you are happy with the fix, I'll close this issue off.
